### ISSUE TITLE
Planner crash  during simulation and optim node on ROS Melodic from src

### ISSUE THREAD

**Issue by tomlogan501** [rst-tu-dortmund/teb_local_planner#211]
Hi,
I tested the planner on the online tutorial of robotignite with the husky : https://www.robotigniteacademy.com/en/course/teb-local-planner/details/

Our lab robot is also a husky with various sensors, I transferred all the parameters to my Gazebo simulation from robotignite tutorial.

I have various problems such as missed loop updates on the simulation.
I tested the optim node and realize that the parameter /test_optim_node/enable_homotopy_class_planning shutdown the optim node when I started playing around on RVIZ.

```
tsimon@GL503GE:~/teb_catkin_ws$ rosparam set /test_optim_node/enable_homotopy_class_planning True
/opt/ros/melodic/lib/python2.7/dist-packages/rosparam/__init__.py:370: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  set_param_raw(param, yaml.load(value), verbose=verbose)
tsimon@GL503GE:~/teb_catkin_ws$ roslaunch teb_local_planner test_optim_node.launch
... logging to /home/tsimon/.ros/log/ee5d56fe-a572-11ea-a3eb-91d3f2cf57d9/roslaunch-GL503GE-29609.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://GL503GE:40715/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    rviz (rviz/rviz)
    test_optim_node (teb_local_planner/test_optim_node)

ROS_MASTER_URI=http://localhost:11311

process[test_optim_node-1]: started with pid [29635]
process[rviz-2]: started with pid [29642]
[ INFO] [1591174894.346716833]: No robot footprint model specified for trajectory optimization. Using point-shaped model.
[test_optim_node-1] process has died [pid 29635, exit code -11, cmd /home/tsimon/teb_catkin_ws/devel/lib/teb_local_planner/test_optim_node __name:=test_optim_node __log:=/home/tsimon/.ros/log/ee5d56fe-a572-11ea-a3eb-91d3f2cf57d9/test_optim_node-1.log].
log file: /home/tsimon/.ros/log/ee5d56fe-a572-11ea-a3eb-91d3f2cf57d9/test_optim_node-1*.log

```
It seems to occur when I had the 2nd obstacle

![image](https://user-images.githubusercontent.com/56969577/83622817-c6f46300-a590-11ea-8958-85c96b3aef2f.png)

Here is the parameter list for the husky

```
controller_frequency: 3.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

TebLocalPlannerROS:

 odom_topic: odometry/filtered
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
    
 # Robot
         
 max_vel_x: 2.0
 max_vel_x_backwards: 2.2
 max_vel_y: 0.0
 max_vel_theta: 2.0
 acc_lim_x: 2.5
 acc_lim_theta: 2.5
 min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

 footprint_model:
   type: "point"

 # GoalTolerance
    
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.75 # This value must also include our robot radius, since footprint_model is set to "point".
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 weight_adapt_factor: 2

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
```

Do you have a docker file to check everything on melodic ? 
Should I check other parameters due to kinetic version on robotignite ?
