### ISSUE TITLE
[ROS2] Update teb_params.yaml in order to properly run tb3 simulation

### ISSUE THREAD

**Issue by Michael-Equi** [rst-tu-dortmund/teb_local_planner#220]
OS: Ubuntu 20.04
Dist: ROS2 Foxy Binaries
Nav2: 69977cd83d9040df3422d8a2e564715b6002f3fb
TEB: 8bd805e29ef629a003880e22d67d9529da76a87d

The current teb_params.yaml in the ros2-master branch does not allow the tb3 simulation to successfully run by preventing the controller node from progressing to an active state. 

### Steps to replicate:
Build the teb_local_planner package for ROS2 Foxy and run `teb_tb3_simulation_launch.py`.

### Update:
I have tried replacing the current parameters with the ones found in issue https://github.com/rst-tu-dortmund/teb_local_planner/issues/203 with little luck, although it does seem to allow the nav2 stack to startup fine.  However, all I get with that configuration is the following output while the tb3 just rotates in place.

```
[bt_navigator-11] [INFO] [1595707851.384197642] [bt_navigator]: Begin navigating from current location to (0.65, 1.84)
[controller_server-8] [INFO] [1595707851.418366655] [controller_server]: Received a goal, begin computing control effort.
[controller_server-8] [INFO] [1595707852.468641585] [controller_server]: Passing new path to controller.
[controller_server-8] [INFO] [1595707853.518666932] [controller_server]: Passing new path to controller.
[controller_server-8] [INFO] [1595707854.518639488] [controller_server]: Passing new path to controller.
[controller_server-8] [INFO] [1595707855.568666246] [controller_server]: Passing new path to controller.
```

**Comment by ghost** [comment]
I'm facing similar issues. Referring to the sample params, I came up with the following params for the tb3 simulations:

```
amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugin_ids: ["DynamicFollowPath"]
    DynamicFollowPath.footprint_model.type: circular
    DynamicFollowPath.footprint_model.radius: 0.17
    DynamicFollowPath.min_obstacle_dist: 0.1
    DynamicFollowPath.inflation_dist: 0.1
    DynamicFollowPath.costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
    DynamicFollowPath.costmap_converter_spin_thread: True
    DynamicFollowPath.costmap_converter_rate: 15.0
    DynamicFollowPath.enable_homotopy_class_planning: True
    DynamicFollowPath.enable_multithreading: True
    #DynamicFollowPath.weight_obstacle: 100.0
    DynamicFollowPath.optimization_verbose: False
    DynamicFollowPath.teb_autoresize: True
    DynamicFollowPath.min_samples: 3.0
    DynamicFollowPath.max_samples: 20.0
    DynamicFollowPath.max_global_plan_lookahead_dist: 1.0
    DynamicFollowPath.visualize_hc_graph: True
    DynamicFollowPath.max_vel_x: 0.26
    DynamicFollowPath.max_vel_theta: 1.0
    DynamicFollowPath.acc_lim_x: 2.5
    DynamicFollowPath.acc_lim_theta: 3.2


costmap_converter:
  ros__parameters:
    use_sim_time: True

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      footprint: "[[-0.085, -0.085], [-0.085, 0.085], [0.085, 0.085], [0.085, -0.085]]"
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.17
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.17
      resolution: 0.05
      footprint: "[[-0.085, -0.085], [-0.085, 0.085], [0.085, 0.085], [0.085, -0.085]]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "turtlebot3_world.yaml"

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True
```

However, as soon as I set the goal pose, I constantly keep getting the following error:

```
[controller_server-4] [ERROR] [1603190336.450116718] [controller_server]: No valid trajectories out of 0! 
[controller_server-4] [WARN] [1603190336.450605379] [controller_server_rclcpp_node]: [follow_path] [ActionServer] Aborting handle.
```

I'm unable to tell if this is because of the params or some issues in the ros2 branch.
