### ISSUE TITLE
lowering the acc_lim_x to be less than 0.01

### ISSUE THREAD

**Issue by ibraEssam** [rst-tu-dortmund/teb_local_planner#237]
Hallo All, 
First of all, thank you for this great package and your time and effort. 
I'm working on a UGV type robot and the requirements are max_vel = 0.05 and max_accel = 0.01 
but I can see that the lower limit of the acceleration in the parameters is 0.01 which makes the robot acts in a jerky way. 
the blue curve is the cmd_vel from teb and the other is from yocs_velocity_smoother  
![teb2](https://user-images.githubusercontent.com/6087928/96772193-11ad3500-13e3-11eb-87fa-36e3c1c57d4b.png)

would changing this lower limit in source code and rebuilding the package has any consecquences or it's safe? 
Thank you and i appreciate your feedback 

```
TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map

  # Trajectory
  teb_autosize: True
  dt_ref: 0.2
  dt_hysteresis: 0.02
  min_samples: 10
  max_samples: 500
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 5.0
  global_plan_viapoint_sep: 0.25
  global_plan_prune_distance: 0.50
  exact_arc_length: False #True
  feasibility_check_no_poses: 4
  publish_feedback: False
  
# Robot
  max_vel_x: 0.05 #0.1
  max_vel_x_backwards: 0.0 #0.01
  max_vel_theta: 0.1 #0.4
  max_vel_y: 0.0
  acc_lim_y: 0.0
  acc_lim_x: 0.01 #0.01
  acc_lim_theta: 0.001 #0.01
  min_turning_radius: 0.0
  wheelbase: 0.0
  cmd_angle_instead_rotvel: False
  footprint_model: 
    type: "two_circles"
    # radius: 0.4
    front_offset: -0.2 # for type "two_circles"
    front_radius: 0.45 # for type "two_circles"
    rear_offset:  0.7 # for type "two_circles"
    rear_radius: 0.45 # for type "two_circles"
    # vertices: [ [0.462, -0.302], [-0.462, -0.302], [-0.462, 0.302], [0.462, 0.302] ]
 
 # GoalTolerance
  xy_goal_tolerance: 0.35
  yaw_goal_tolerance: 0.35
  free_goal_vel: True
  complete_global_plan: True
 
# Obstacles
  min_obstacle_dist: 0.05
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1
  obstacle_poses_affected: 15
  inflation_dist: 0.1
  legacy_obstacle_association: True
  costmap_converter_plugin: ""
 
 # Optimization
  no_inner_iterations: 3
  no_outer_iterations: 2
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.001
  obstacle_cost_exponent: 5
  weight_max_vel_x: 3
  weight_max_vel_theta: 10
  weight_acc_lim_x: 4
  weight_acc_lim_theta: 10
  weight_kinematics_nh: 1000  #75 ?? 1000 pare sa fie
  weight_kinematics_forward_drive: 1000 #10
  weight_optimaltime: 1.0
  weight_shortest_path: 0
  weight_obstacle: 100
  weight_inflation: 0.2
  weight_dynamic_obstacle: 100
  weight_dynamic_obstacle_inflation: 0.5
  weight_viapoint: 50.0 #was 1.0
  weight_adapt_factor: 2
  
# Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: True
  max_number_classes: 2
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.9
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 7.5
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: True
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False
  
# Recovery
  shrink_horizon_backup: True
  shrink_horizon_min_duration: 15
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 20
  oscillation_filter_duration: 20
```
