### ISSUE TITLE
TEB plan the terrible results without HPC

### ISSUE THREAD

**Issue by Astaxuqichao** [rst-tu-dortmund/teb_local_planner#361]
When i use test_optim_node and change footprint model, the TEB sometimes get a terrible result and seem to ignore the footprint (HPC 
 closed).The trajectory is closed to obstacle , even it will follow obstacle moving.

My parameters are as follows , and others are default:
```
min_obstacle_dist: 0.1
enable_homotopy_class_planning: false
footprint_model:
  type: "polygon"
  vertices: [[-0.525, -0.52], [-0.525, 0.52], [0.525, 0.52], [0.525, -0.52]]
```
![Screenshot from 2022-04-07 10-35-00](https://user-images.githubusercontent.com/71440351/162109186-750885c9-8435-4a66-bb52-99a19bf4fd6b.png)

![Peek 2022-04-07 10-42](https://user-images.githubusercontent.com/71440351/162109793-589c5282-d650-4eef-ad2a-f5ac6e2a6ede.gif)
